name: Not Cocoa 
markdown: redcarpet
destination: /home/mcormier/sites/weblog
pygments: true
permalink: /:year/:title.html
exclude: [monitor.sh, desktop.sh, todo.md]

# For the RSS generator
url: http://weblog.preenandprune.com
author: Matthieu Cormier
