name: Not Cocoa 
markdown: redcarpet
destination: /home/mcormier/sites/weblog
pygments: true
permalink: /:year/:title.html


# For the RSS generator
url: http://webblog.preenandprune.com
author: Matthieu Cormier
